# -*- coding: utf-8 -*-
"""rsp_group_14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aI7r30Qv0epEKSSJbvhtB4MpygowqJz1
"""

import timeout_decorator  # 事前にpipでインストールしておく
import time
import numpy as np
import random
import math

class RSP_Agent_1:
    def __init__(self,num_match=10000):  # インスタンス変数self.cnt,self.my_hands,self.oppo_hands,self.num_matchだけは固定。その他は自由に削除、追加OK.
        self.cnt = 0  # カウンター（今の相手と何回対戦したか）
        self.my_hands = []  # 自分の手の記録
        self.oppo_hands = []  # 相手の手の記録
        self.num_match = num_match  # 何回対戦するか
        """
        グー(Rock)、チョキ(Scisors)、パー(Paper)はそれぞれ0,1,2に割り当てる
        """

        rng = np.random.default_rng()  # 乱数生成器の実体化（seedの値を工夫するというのもアリかも）
        self.my_hand = rng.integers(0,3)  # agent0の性質「特定の手をひたすら出し続ける」をxで指定

    @timeout_decorator.timeout(1)  # このdecoratorは固定。触らない。
    def output_hand(self):  # この関数名は固定。中身は自由に改変可。
        # 戻り値（hand)については必ずself.my_hands.append(hand)として記録する。
        # 戦略の決定：ここが一番工夫するところ
        # self.my_hands,self.oppo_handsを使ってこの関数をうまく作ることが課題

        # 手の決定
        hand = self.my_hand

        self.my_hands.append(hand)  # この行は必須：戻り値をmy_handsに追加する
        return hand

    def get_hand(self,oppo_hand):  # この関数名は固定。中身も触らない。
        self.cnt += 1
        self.oppo_hands.append(oppo_hand)


class RSP_Agent_2:
    def __init__(self,num_match=10000):  # インスタンス変数self.cnt,self.my_hands,self.oppo_hands,self.num_matchだけは固定。その他は自由に削除、追加OK.
        self.cnt = 0  # カウンター（今の相手と何回対戦したか）
        self.my_hands = []  # 自分の手の記録
        self.oppo_hands = []  # 相手の手の記録
        self.num_match = num_match  # 何回対戦するか
        """
        グー(Rock)、チョキ(Scisors)、パー(Paper)はそれぞれ0,1,2に割り当てる
        """

        rng = np.random.default_rng()  # 乱数生成器の実体化（seedの値を工夫するというのもアリかも）
        self.my_hand = rng.integers(0,3)  # agent0の性質「特定の手をひたすら出し続ける」をxで指定

    @timeout_decorator.timeout(1)  # このdecoratorは固定。触らない。
    def output_hand(self):  # この関数名は固定。中身は自由に改変可。
        # 戻り値（hand)については必ずself.my_hands.append(hand)として記録する。
        # 戦略の決定：ここが一番工夫するところ
        # self.my_hands,self.oppo_handsを使ってこの関数をうまく作ることが課題

        # 手の決定
        hand = self.my_hand

        self.my_hands.append(hand)  # この行は必須：戻り値をmy_handsに追加する
        return hand

    def get_hand(self,oppo_hand):  # この関数名は固定。中身も触らない。
        self.cnt += 1
        self.oppo_hands.append(oppo_hand)


class RSP_Agent_3:
    def __init__(self,num_match=10000):  # インスタンス変数self.cnt,self.my_hands,self.oppo_hands,self.num_matchだけは固定。その他は自由に削除、追加OK.
        self.cnt = 0  # カウンター（今の相手と何回対戦したか）
        self.my_hands = []  # 自分の手の記録
        self.oppo_hands = []  # 相手の手の記録
        self.num_match = num_match  # 何回対戦するか
        """
        グー(Rock)、チョキ(Scisors)、パー(Paper)はそれぞれ0,1,2に割り当てる
        """

        rng = np.random.default_rng()  # 乱数生成器の実体化（seedの値を工夫するというのもアリかも）
        self.my_hand = rng.integers(0,3)  # agent0の性質「特定の手をひたすら出し続ける」をxで指定

    @timeout_decorator.timeout(1)  # このdecoratorは固定。触らない。
    def output_hand(self):  # この関数名は固定。中身は自由に改変可。
        # 戻り値（hand)については必ずself.my_hands.append(hand)として記録する。
        # 戦略の決定：ここが一番工夫するところ
        # self.my_hands,self.oppo_handsを使ってこの関数をうまく作ることが課題

        # 手の決定
        hand = self.my_hand

        self.my_hands.append(hand)  # この行は必須：戻り値をmy_handsに追加する
        return hand

    def get_hand(self,oppo_hand):  # この関数名は固定。中身も触らない。
        self.cnt += 1
        self.oppo_hands.append(oppo_hand)